Merge csv outputs
APHA-CSU/BovTB-nf pull request #21
Opened 2021-02-03 23:25 UTC by ellisrichardj

I've added an additional process to merge the csv output files and determine whether samples are M.bovis positive or not.  Still working on the unit test for this but thought that could be done in a separate branch.

2021-02-08 09:54 UTC, afishman reviewed
overall approach seems good. Most of the feedback is on style an conventions. It'd be great to see some unit tests as well. This is a nice warmup problem

2021-02-08 09:54 UTC, afishman commented on bTB-WGS_process.nf
> +	python3 $pypath/CombineCsv.py Assigned.csv Qbovis.csv ${params.DataDir}
This should be in `bin/` like the other processes. You can remove the `python3 $pypath/` part

2021-02-08 09:54 UTC, afishman commented on pyscripts/CombineCsv.py
> +import pandas as pd
Add `#!/usr/local/bin/python` to the top. As well as a brief description of what it does. Eg see https://github.com/APHA-CSU/BovTB-nf/blob/master/tests/utils/print_csv_value.py

2021-02-08 09:54 UTC, afishman commented on pyscripts/CombineCsv.py
> +FinalOut.to_csv(""+str(SeqRun)+"_FinalOut_"+str(DateOut)+".csv")
It's convention to add ` if __name__ == '__main__':` here to make this module easier to import. See: https://stackoverflow.com/questions/419163/what-does-if-name-main-do

2021-02-08 09:54 UTC, afishman commented on pyscripts/CombineCsv.py
> +In1 = sys.argv[1]
I'd put arg parsing in the `if __name__ == '__main__'` section. Sometimes you might want to use inputs that don't come from the command-line. 

You could also try using [argparse ](https://github.com/APHA-CSU/BovTB-nf/blob/master/tests/utils/print_csv_value.py)if you wanted - but that's less of a big deal.

2021-02-08 09:54 UTC, afishman commented on pyscripts/CombineCsv.py
> +
The rest of the script you can probably wrap up into a function. E.g. `def combine(assigned, csv_path, sequence_run)`

2021-02-08 09:54 UTC, afishman commented on pyscripts/CombineCsv.py
> +DateOut = date.today().strftime('%d%b%y')
We should be consistent with our naming conventions. The python code I wrote in `tests/utils/` follows the pep8 standard: the common standard. https://www.python.org/dev/peps/pep-0008/

Variable names should be lowercase underscore. E.g `date_out`

2021-02-08 09:54 UTC, afishman commented on pyscripts/CombineCsv.py
> +Qbovis.loc[(Qbovis['TotalReads'] > 500) & (Qbovis['Abundance'] < 1), 'ID'] = 'Inconclusive'
You should DRY up this hardcoded value. A couple of option for this:
- a global variable just below the imports called something like `threshold = 500`.
- An optional argument. `def combine(assigned, csv_path, sequence_run, threshold=500)`
- An optional command-line argument. `parser.add_argument('threshold', default=500, help='blah')`

2021-02-08 09:54 UTC, afishman commented on pyscripts/CombineCsv.py
> +FinalOut.to_csv(""+str(SeqRun)+"_FinalOut_"+str(DateOut)+".csv")
Can we perhaps use a simpler csv naming convention?

2021-02-08 14:07 UTC, ellisrichardj commented on bTB-WGS_process.nf
> +	python3 $pypath/CombineCsv.py Assigned.csv Qbovis.csv ${params.DataDir}
Done

2021-02-08 17:13 UTC, ellisrichardj commented on pyscripts/CombineCsv.py
> +FinalOut.to_csv(""+str(SeqRun)+"_FinalOut_"+str(DateOut)+".csv")
I need the csv name to reflect show the seqneucer run number and the date the output was processed.  This avoids conflicts if the same data is processed on different days

2021-02-08 17:13 UTC, ellisrichardj commented
Refactored CombineCsv.py to address your comments - thanks, I learnt a lot!

2021-02-09 15:25 UTC, afishman requested changes

2021-02-09 15:25 UTC, afishman commented on bTB-WGS_process.nf
> +	CombineCsv.py Assigned.csv Qbovis.csv ${params.DataDir}
Can you rename this to combineCsv.py? I know it sounds picky but that's the convention in `bin/`

2021-02-09 15:25 UTC, afishman commented on bin/CombineCsv.py
> +date_out = date.today().strftime('%d%b%y')
This should go in `combine()`.

Currently this line runs once on module import. If someone imports this module runs `combine()` multiple times, `date_out` won't update

2021-02-09 15:25 UTC, afishman commented on bin/CombineCsv.py
> +    # Fill empty value cells with zero
Can you add a brief description of the bug we talked over the phone? (as well as any others you think may also exist here). 
Convention I'm used to is if there's a bug, or shortcoming you know about but don't want to fix yet, you should add a searchable comment like 
`BUG: Might give spurious results if <blah>`
or 
`TODO: default 'ID' required to cover all logical cases`

2021-02-09 15:25 UTC, afishman commented on bin/CombineCsv.py
> +    parser.add_argument('read_threshold', nargs='?', type=int, default=500, help='threshold for number of M.bovis reads')
FYI another way to do optional arguments on argparse is with something like 
`parser.add_argument('--read_threshold', type=int, default=500, help='threshold for number of M.bovis reads')`

Though I'm fine with what you prefer

2021-02-09 15:25 UTC, afishman commented on bin/CombineCsv.py
> +    finalout_df.to_csv(""+str(seq_run)+"_FinalOut_"+str(date_out)+".csv")
Two more readable ways to write this:
- `"%s_FinalOut_%s.csv" % (seq_run, date_out)`
- `"{}_FinalOut_{}.csv".format(seq_run, date_out)`

2021-02-09 16:05 UTC, ellisrichardj commented on bin/CombineCsv.py
> +date_out = date.today().strftime('%d%b%y')
Done

2021-02-09 16:07 UTC, ellisrichardj commented on bin/CombineCsv.py
> +    finalout_df.to_csv(""+str(seq_run)+"_FinalOut_"+str(date_out)+".csv")
Done - second option

2021-02-09 16:09 UTC, ellisrichardj commented on bin/CombineCsv.py
> +    parser.add_argument('read_threshold', nargs='?', type=int, default=500, help='threshold for number of M.bovis reads')
Thanks - makes sense

2021-02-09 16:10 UTC, ellisrichardj commented on bin/CombineCsv.py
> +    parser.add_argument('read_threshold', nargs='?', type=int, default=500, help='threshold for number of M.bovis reads')
Thanks, I like this version

2021-02-09 17:10 UTC, ellisrichardj commented on bin/CombineCsv.py
> +    # Fill empty value cells with zero
Added in the comment to describe the issue

2021-02-09 17:16 UTC, ellisrichardj commented on bTB-WGS_process.nf
> +	CombineCsv.py Assigned.csv Qbovis.csv ${params.DataDir}
Done

2021-02-09 17:25 UTC, ellisrichardj commented
Updated as requested

2021-02-10 09:39 UTC, afishman approved these changes
Excellent bit of work. Looks very nice. Well done. 🙂

2021-02-10 11:49 UTC, merged