Fix id non bovis
APHA-CSU/BovTB-nf pull request #23
Opened 2021-02-10 17:53 UTC by ellisrichardj

This PR fixes an issue that I noticed where the idNonBovis was not running correctly after being moved to a standalone script.  I picked this up running samples which do not 'Pass'.  There were a number of problems, but they have all been fixed:
- Additional parameters (kraken2db and lowmem) were required when calling the script - without them kraken fails and does not produce the output for bracken.  
- Bracken also required the kraken2db parameter (and the kraken output!).  
- In addition to bracken being linked in /usr/local/bin, the bracken/src/ directory also need to be linked.
- the awk command failed as the variables were escape (which was essential to get it running as a script embedded in nextflow)

2021-02-11 09:25 UTC, afishman requested changes

2021-02-11 09:25 UTC, afishman commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
I don't think we should symlink the `src` directory to any `bin/`. It's too generic and it's not an executable. 

Does this even make Bracken work?

2021-02-11 11:52 UTC, ellisrichardj commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
I don't like it either, but unfortunatley this is the way Bracken is set up to work - see https://github.com/jenniferlu717/Bracken#hard-bracken-installation

2021-02-11 12:00 UTC, ellisrichardj commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
The call to src/est_abundance.py is hardcoded in the bracken file

2021-02-11 12:31 UTC, afishman commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
you can put this code in a file called something better than  `my-bracken` and then symlink `my-bracken` to `usr/local/bin`

```
#!/bin/sh

cd /biotools/Bracken-2.6.0/
echo $PWD
./bracken "$@"
```

2021-02-11 13:05 UTC, ellisrichardj commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
So if I add this to BovTB-nf/bin (as runBracken.bash??), what's the path I need to link in Dockerfile?

2021-02-11 13:16 UTC, ellisrichardj commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
I'm guessing it would come after cloning the repo and look something like
`ln -s $BOVTB_PATH/bin/runBracken.bash /usr/local/bin/runBracken.bash`

2021-02-11 13:49 UTC, afishman commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
I see what you mean. I would probably put the script in the `docker/` directory in a file called `docker/bracken.sh`

Then, in the `Dockerfile` you can replace the existing symlink with something like
```
cp $BOVTB_PATH/docker/bracken.sh $BIOTOOLS_PATH/Bracken-2.6.0/
chmod +x $BIOTOOLS_PATH/Bracken-2.6.0/bracken.sh
ln -s $BIOTOOLS_PATH/Bracken-2.6.0/bracken.sh /usr/local/bin/bracken
```

2021-02-11 13:55 UTC, ellisrichardj commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
But won't this fail at that point in the docker build as the repo doesn't get cloned until the end?

2021-02-11 14:10 UTC, afishman commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
ah yeah good point. You can use the `COPY` directive instead.

```
COPY ./docker/bracken.sh $BIOTOOLS_PATH/Bracken-2.6.0/
```

2021-02-15 22:10 UTC, ellisrichardj commented
```diff
diff --git a/docker/Dockerfile b/docker/Dockerfile
index a2996c6..45cfd47 100644
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -125,10 +125,7 @@ RUN wget https://github.com/jenniferlu717/Bracken/archive/v2.6.0.tar.gz && \
     rm -f v2.6.0.tar.gz && \
     cd Bracken-2.6.0 && \
     sh ./install_bracken.sh ../bracken && \
-    cd .. && \
-    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/bracken /usr/local/bin/bracken && \
-    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
-
+    cd ..
 
 # Install nextflow.
 COPY ./docker/install_nextflow-20.7.1.bash ./install_nextflow.bash
@@ -151,6 +148,7 @@ WORKDIR $BOVTB_PATH
 
 # Copy repository
 COPY ./ ./
-RUN chmod +x ./bin/*
+RUN chmod +x ./bin/* && \
+    ln -s $BOVTB_PATH/docker/runBracken.bash /usr/local/bin/bracken
 
 CMD nextflow run bTB-WGS_process.nf --outdir "/results/" --reads "/reads/*_{S*_R1,S*_R2}*.fastq.gz" -with-report "/results/report.html"
diff --git a/docker/runBracken.bash b/docker/runBracken.bash
new file mode 100644
index 0000000..042d336
--- /dev/null
+++ b/docker/runBracken.bash
@@ -0,0 +1,5 @@
+#!/bin/bash
+
+cd /biotools/Bracken-2.6.0/
+echo $PWD
+./bracken "$@"
\ No newline at end of file

```

2021-02-15 22:52 UTC, ellisrichardj commented on docker/Dockerfile
> +    ln -s $BIOTOOLS_PATH/Bracken-2.6.0/src /usr/local/bin/src
Added a comment to look at this again.  Other approaches seem a bit to complex to me

2021-02-16 09:38 UTC, afishman approved these changes
Thanks for cleaning up the bugs I introduced while refactoring :)

2021-02-16 11:04 UTC, merged