Add log info
APHA-CSU/BovTB-nf pull request #26
Opened 2021-03-01 23:36 UTC by ellisrichardj

I have added some minimal log info (user, commit id) to the output file.  I have used the inbuilt nextflow properties and appended them to the combined csv.  I think this will be useful for traceability and accreditation.

2021-03-02 10:26 UTC, afishman requested changes

2021-03-02 10:26 UTC, afishman commented on bin/combineCsv.py
> +def combine(assigned_csv, bovis_csv, seq_run, user, commit, read_threshold, abundance_threshold):
We can get this information directly from python (requires gitpython):
```
import getpass
import git
user = getpass.getuser()

repo = git.Repo(search_parent_directories=True)
sha = repo.head.object.hexsha
```

See: https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script
and: https://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python

2021-03-02 10:26 UTC, afishman commented on bin/combineCsv.py
> +    with open("{}_FinalOut_{}.csv".format(seq_run, date_out), "a") as outFile:
Appending non-csv data to a csv file will make the file cumbersome to parse. 

How about saving this to a new file instead (e.g. `metadata.json` or `metadata.txt`)?

2021-03-02 10:26 UTC, afishman commented on bin/readStats.bash
> +        elif [[ ${avg_depth%%.*} -lt $mindepth ]] && [[ ${pc_mapped%%.*} -lt $minpc ]] && [[ $num_trim -gt $minreads ]]; then flag="Contaminated"
Great to see this spelling corrected! Need to update the unit test to make them pass. `tests/jobs/lod.bash` line 16

2021-03-02 11:42 UTC, afishman requested changes

2021-03-02 11:42 UTC, afishman commented on bTB-WGS_process.nf
> +	combineCsv.py Assigned.csv Qbovis.csv ${params.DataDir} ${workflow.userName} ${workflow.commitId}
Simpler to have less input args - can get this info from python (see below)

2021-03-05 00:20 UTC, ellisrichardj commented on bin/combineCsv.py
> +def combine(assigned_csv, bovis_csv, seq_run, user, commit, read_threshold, abundance_threshold):
Thanks for this.  I have added an extra line to ensure that the repo sha is captured when running the script from a different directory

2021-03-05 00:21 UTC, ellisrichardj commented on bin/combineCsv.py
> +    with open("{}_FinalOut_{}.csv".format(seq_run, date_out), "a") as outFile:
As discussed have kept like this to ensure tracability for accrediation

2021-03-05 00:22 UTC, ellisrichardj commented on bin/readStats.bash
> +        elif [[ ${avg_depth%%.*} -lt $mindepth ]] && [[ ${pc_mapped%%.*} -lt $minpc ]] && [[ $num_trim -gt $minreads ]]; then flag="Contaminated"
Good spot - now fixed

2021-03-08 13:21 UTC, ellisrichardj commented on bTB-WGS_process.nf
> +	combineCsv.py Assigned.csv Qbovis.csv ${params.DataDir} ${workflow.userName} ${workflow.commitId}
Have changed to your suggestion

2021-03-08 13:22 UTC, ellisrichardj commented on bTB-WGS_process.nf
> +	combineCsv.py Assigned.csv Qbovis.csv ${params.DataDir} ${workflow.userName} ${workflow.commitId}
Changed as suggester

2021-03-08 13:24 UTC, ellisrichardj reviewed
Made changes as agreed

2021-03-08 14:16 UTC, afishman approved these changes
Fantastic work. Just remember to use underscores when naming python variables in the future. Strictly speaking `scriptpath` should probably be `script_path`

2021-03-08 16:04 UTC, merged